google-datacatalog-looker-connector/setup.py
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/sync/metadata_synchronizer.py

Added logic to handle `error.SDKError` on `scrape_query_generated_sql`, some Looker instances may have queries not pointing to their generated_sql. So we need to handle the `error.SDKError`, if it does not exist, the generated_sql will be ignored.
Added `scrape_query_generated_sql ` to `error.SDKError` try/except handler.
Run the connector on a Looker instance with inconsistent query information.
Added logic to handle `error.SDKError` on `scrape_query_generated_sql`.
Fixes #17

Looker - FIX/get query error

---

google-datacatalog-looker-connector/cloudbuild.yaml
google-datacatalog-looker-connector/system_tests/assert.sh
google-datacatalog-looker-connector/system_tests/cleanup.sh
google-datacatalog-looker-connector/system_tests/cleanup_results_test.py
google-datacatalog-looker-connector/system_tests/execution_results_test.py
google-datacatalog-looker-connector/tools/cleanup_datacatalog.py
google-datacatalog-tableau-connector/cloudbuild.connector.yaml
google-datacatalog-tableau-connector/system_tests/cleanup.sh

- What I did
Updated the system-tests directories path. Since we changed to a mono-repo, the system tests were disabled. Updating the new path so we can enable them.
- How I did it
Each connector uses its local directory to run system tests.
- How to verify it
Trigger system-tests.
- Description for the changelog
UPDATE system-tests connectors path.

UPDATE system-tests connectors path 

---

google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/constant.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory_test.py

Closes #19 
Started using `BaseEntryFactory`'s id and display name formatters.
Changed the `DataCatalogEntryFactory` class in order to make it child of `google.datacatalog_connectors.commons.prepare.base_entry_factory.BaseEntryFactory`. Then, called the parent class `_format_id()` and `_format_display_name()` methods.
Run the automated and maybe manual tests.
Use BaseEntryFactory's id and display name formatters

Use BaseEntryFactory's id and display name formatters

---

tools/create-current-version-tags.sh
tools/release-create-tags.sh

Added script to automatically create tags on release process.
Created the bash script `tools/release-create-tags.sh`.
Run the release tagging step of the release process using the `tools/release-create-tags.sh` script. Afterwards verify the tags were created.
Added script to automatically create tags on release process.

ADD auto tagging script for release process

---

google-datacatalog-looker-connector/setup.py
google-datacatalog-tableau-connector/setup.py
tools/create-current-version-tags.sh

Set fixed versions before datacatalog v2 client breaking change
Fixed dependencies versions on `setup.py`, so it's going to use versions before v2 client breaking change.
Install rdbms connectors from PyPI
Set fixed versions before datacatalog v2 client breaking change

Set fixed versions before datacatalog v2 client breaking change 

---

google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/sync/metadata_synchronizer.py

Added logs to make the Looker metadata sync process clearer.
Added counters and `log.info()` statements to `datacatalog_connectors/looker/sync/metadata_synchronizer.py`.
Added logs to make the Looker metadata sync process clearer.

Improve the Looker sync stage output

---

.github/workflows/pythonpackage.yml
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/setup.cfg
google-datacatalog-qlik-connector/setup.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/metadata_scraper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/repository_services_api_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/authenticator_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/metadata_scraper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/repository_services_api_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/scrape_ops_mocks.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py

Added elementary code to consume the Engine API
The most relevant changes are:
1. Added the `prepare.EngineAPIHelper` class. It wraps requests to the Qlik Engine JSON API.
1. Changed the `prepare.MetadataScraper` class, adding code that enables it to scrape Sheets by consuming the Qlik Engine JSON API.
Run the unit tests and/or the connector and take a look at the output logs. The below lines are expected to be in part of the output:
```
...
INFO:root:Objects to be scraped: Streams, Apps, and Sheets
INFO:root:
INFO:root: . Scraping Sheets from "Qlik to GCP Test"
INFO:root: .. The App has 5 Sheets
INFO:root:
INFO:root: . Scraping Sheets from "Sample App"
INFO:root: .. The App has 3 Sheets
INFO:root:
INFO:root:==== DONE …
```

Add elementary code to consume the Engine API

---

google-datacatalog-looker-connector/tools/scripts/cleanup_datacatalog.py
google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/constants.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/metadata_scraper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/metadata_scraper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/scripts/cleanup_datacatalog.py
google-datacatalog-tableau-connector/tools/scripts/cleanup_datacatalog.py

Added support for ingesting Sheets metadata. This PR is part of the effort to deliver #34.
Added code to create Custom Entries, Tag Template, and Tags to store Sheets metadata.
Run the connector following the instructions from the README file.
Added support for ingesting Sheets metadata

Add support for ingesting Sheets metadata

---

google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py

Improved the checks before setting the `publish_time` Tag field value to avoid using invalid input.
Checked whether the Apps and Sheets were published before setting the value of the `publish_time` Tag field.
Improved the checks before setting the `publish_time` Tag field value to avoid using invalid input.

Improve checks before setting the publish_time field

---

google-datacatalog-tableau-connector/setup.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory_test.py

Added a temporary workaround to avoid breaking the metadata ingestion flow when there are characters in the site name that are not compatible with the `entry.linked_resource` field. This is part of the effort to fix https://github.com/GoogleCloudPlatform/datacatalog-connectors-bi/issues/43 and I'm going to start working on the definitive fix ASAP.
Used a regular expression to replace invalid chars with a `_`.
Non-compliant Linked Resource chars temporarily replaced with an underscore.

Replace non-compliant Linked Resource chars

---

google-datacatalog-tableau-connector/docs/developer-resources/postman.md
google-datacatalog-tableau-connector/setup.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/scrape/authenticator.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/scrape/constants.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/scrape/metadata_api_helper.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/scrape/metadata_scraper.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/scrape/rest_api_helper.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/sync/metadata_synchronizer.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/sync/sites_synchronizer.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/sync/workbooks_synchronizer.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/tableau2datacatalog_cli.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/scrape/authenticator_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/scrape/metadata_api_helper_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/scrape/metadata_scraper_mocks.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/scrape/metadata_scraper_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/scrape/rest_api_helper_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/sync/dashboards_synchronizer_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/sync/metadata_synchronizer_mocks.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/sync/metadata_synchronizer_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/sync/sites_synchronizer_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/sync/workbooks_synchronizer_test.py
google-datacatalog-tableau-connector/tools/postman/Tableau GraphQL API.postman_collection.json
google-datacatalog-tableau-connector/tools/postman/Tableau REST API.postman_collection.json
google-datacatalog-tableau-connector/tools/postman/tableau-sample-environment.postman_environment.json

1. Changed the Metadata API scrape results in order to inject the `contentUrl` field into `site` objects.
1. Changed the Data Catalog Entry factory to use this new field when generating the `entry.linkedResource` field.
This PR closes #43.
1. Added the `MetadataAPIHelper.__add_site_content_url_field()` method and called it at the end of all public methods of the class.
1. Fixed the `DataCatalogEntryFactory.__format_site_content_url()` method to use the site `contentUrl` instead of the name.
I'm also leveraging this PR to add some improvements to the Tableau connector:
1. The authentication workflows are now fully managed by the API Helper classes to keep consistency with other BI connectors.
1. The scrape result logs are now fully managed by the …

Use site contentUrl to generate the Linked Resources

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/metadata_scraper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/repository_services_api_helper.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/metadata_scraper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/repository_services_api_helper_test.py

Added the elementary code to scrape Custom Property Definitions. The current scrape/prepare/ingest workflow has not been changed yet.
Added the `scrape_all_custom_property_definitions()` method to `MetadataScraper` class and `get_full_custom_property_definition_list()` to the `RepositoryServicesAPIHelper`.
Added elementary code to scrape Custom Property Definitions.

Scrape Custom Property Definitions

---

google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/constants.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/postman/Qlik Sense Repository Service API.postman_collection.json

Added support to ingest metadata from the Custom Property Definitions.
1. Added new code to the `MetadataSynchronizer` in order to include the scrape/prepare/ingest steps for Custom Property Definitions metadata.
1. Added code to make the related Entries, Tag Templates, and Tags.
1. Added/updated the unit tests.
Run the unit tests and the connector in an integrated environment.
Added support to ingest metadata from the Custom Property Definitions.

Add support to ingest Custom Prop Definitions

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/constants.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/dynamic_properties_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/dynamic_properties_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/scripts/cleanup_datacatalog.py

Added the required code to create Tags for Custom Property Values.
Added a mechanism that creates a new Tag Template for each `choiceValue` found in the Custom Property Definitions. Then, such Tag Templates are used to store all metadata from the Custom Property Values. Each Value is stored as a Tag.
Please notice the `qlik/prepare/dynamic_properties_helper.py` file might be part of the commons package. Maybe we can move it as a follow-up change.
Run the unit tests or, preferably, the Qlik Sense connector against a Qlik site that contains Streams and Apps with Custom Properties. Then, check the Tags created for such assets.
Added support for creating Tags for Custom Property Values

Create Tags for Custom Property Values

---

google-datacatalog-looker-connector/README.md
google-datacatalog-looker-connector/cloudbuild.yaml
google-datacatalog-looker-connector/setup.py
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/scrape/metadata_scraper.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/assembled_entry_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/datacatalog_entry_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/datacatalog_tag_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/scrape/metadata_scraper_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/sync/metadata_synchronizer_test.py

Fixed "Requires authentication" error when Looker connector ran for too long 2 hours~.
- Upgraded looker_sdk to latest version `looker_sdk == 0.1.3b20`.
- Changed client initialization logic to use `init31` for API 3.1.
Run the looker connector in a looker server that has 5000+ assets, and takes more than 2 hours to scrape all assets.
In the latest version the sdk seems to automatically renew the session token, I was able to scrape a looker server that took more than 3 hours, and the error does not happen anymore. Fixes #32.

FIX "Requires authentication" error when Looker connector ran for too long 2 hours~

---

google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/base_engine_api_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_dimensions_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_scraper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_sheets_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/scrape_ops_mocks.py

Changed the `AsyncContextManager` mock in order to enable more realistic scenarios.
1. Added a `__stop_itr_on_no_data` flag that will let the context manager know whether iteration should stop on no more data available or keep sending empty responses when requested. This is not what an actual WebSocket does: it simply does not send any response, but keeps the communication channel open. I didn't find a way to emulate this behavior yet. 
2. Changed the `close` method to force the flag value to `True`; hence stopping the iteration as an actual `websocket.close()` call does.
3. Updated existing unit tests to leverage the new `stop_itr_on_no_data` argument.
Changed the …

Turn async unit tests more realistic

---

google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_dimensions_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_sheets_helper.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/base_engine_api_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_dimensions_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_sheets_helper_test.py

Fixed minor issues in the Qlik metadata scraping
1. In `scrape.base_engine_api_helper_test.py` I've replaced `base_engine_api_helper.BaseEngineAPIHelper._run_until_complete` with `asyncio.new_event_loop().run_until_complete` to avoid calling two methods of the class under test, where possible.
2. In `srape.engine_api_dimensions_helper_test.py` I've detailed the comments on not mocked stuff to let folks know what could be improved in the future towards more granular testing. I'm not sure if I will have the bandwidth to tackle such improvement in the current engagement.
Fixed minor issues in the Qlik metadata scraping.

Fix minor issues in the Qlik metadata scraping

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/constants.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/scripts/cleanup_datacatalog.py

Added support for ingesting Dimensions metadata.
1. Added Dimension-related methods to the Qlik connector's Entry, Tag Template, and Tag factories.
2. Added Dimension-related code to the Qlik connector's metadata synchronizer.
3. Added unit tests to fully cover the above changes.
4. Updated the cleanup script in order to delete the Tag Template identified by `qlik_dimension_metadata`.
5. Added `Master Items: Dimension` to the assets list in the `README.md` file.
Run the unit tests and, preferably, the connector in an integrated environment.
Added support for ingesting Dimensions metadata.

Add support for ingesting Dimensions metadata

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/constants.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/scripts/cleanup_datacatalog.py

Added support for ingesting Measures metadata.
1. Added Measure-related methods to the Qlik connector's Entry, Tag Template, and Tag factories.
2. Added Measure-related code to the Qlik connector's metadata synchronizer.
3. Added unit tests to fully cover the above changes.
4. Updated the cleanup script in order to delete the Tag Template identified by `qlik_measure_metadata`.
5. Added `Master Items: Measure` to the assets list in the `README.md` file.
Run the unit tests and, preferably, the connector in an integrated environment.
Added support for ingesting Measures metadata.

Add support for ingesting Measures metadata

---

google-datacatalog-qlik-connector/setup.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_scraper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_visualizations_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/metadata_scraper.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_scraper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_visualizations_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/metadata_scraper_test.py

Added support for scraping Visualizations (Master Items) metadata.
1. Added the `EngineAPIVisualizationsHelper` class, which is very similar to `EngineAPIDimensionsHelper`.
2. Added the `get_visualizations()` method to the `EngineAPIScraper`.
3. Added the `scrape_visualizations()` method to the `MetadataScraper`.
4. Added unit tests to cover all the changes listed above.
Added support for scraping Visualizations (Master Items) metadata.

Add support for scraping Visualizations metadata

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/setup.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/constants.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/assembled_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/entry_relationship_mapper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/scripts/cleanup_datacatalog.py

Added support for ingesting Visualizations metadata.
1. Added Visualization-related methods to the Qlik connector's Entry, Tag Template, and Tag factories.
2. Added Visualization-related code to the Qlik connector's metadata synchronizer.
3. Added unit tests to fully cover the above changes.
4. Updated the cleanup script in order to delete the Tag Template identified by qlik_visualization_metadata.
5. Added `Master Items: Visualization` to the assets list in the `README.md` file.
Run the unit tests and, preferably, the connector in an integrated environment.
Added support for ingesting Visualizations metadata.
Closes #34.

Add support for ingesting Visualizations metadata

---

google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/base_engine_api_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_dimensions_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_measures_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_sheets_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_visualizations_helper.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_dimensions_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_measures_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_scraper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_sheets_helper_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/scrape/engine_api_visualizations_helper_test.py

Changed `scrape.BaseEngineAPIHelper._run_until_complete()` in order to cancel all tasks running in a given event loop regardless of the type of the exception type that might be raised during the asynchronous code execution.
The main change consists of replacing `except asyncio.TimeoutError:` with `except Exception:` in the aforementioned method. All other changes are consequences of it.
Please notice timeouts are now logged and bypassed at the child-class level. Other exceptions are raised, as they used to be before the changes.
```python
if isinstance(e, asyncio.TimeoutError):
return []
else:
raise
```
Run the unit tests and preferably the connector in an integrated environment.
Improved the …

Improve the exception handling

---

google-datacatalog-qlik-connector/setup.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py

Set the order of the Tag Template fields, so their related Tag fields will always be displayed in the same order in the Data Catalog UI.
By specifying a value for the `order` attribute of all Tag Template fields.
Run the connector in an integrated environment. Then, verify the order of the Tags fields to make sure they are presented in the same order they were added to their respective Tag Templates.
Set the order of the Tag Template fields

Set the order of the Tag Template fields

---

google-datacatalog-qlik-connector/docs/developer-resources/qlik-apis.md

Fixed the Qlik Engine API explorer URL in the docs.
Enclosed the URL in backticks so it's displayed accordingly.
View the `google-datacatalog-qlik-connector/docs/developer-resources/qlik-apis.md` file.
Fixed the Qlik Engine API explorer URL in the docs.

Fix the Qlik Engine API explorer URL in the docs

---

.github/workflows/pythonpackage.yml
google-datacatalog-sisense-connector/.coveragerc
google-datacatalog-sisense-connector/.gitignore
google-datacatalog-sisense-connector/README.md
google-datacatalog-sisense-connector/docs/README.md
google-datacatalog-sisense-connector/docs/developer-resources/README.md
google-datacatalog-sisense-connector/docs/developer-resources/postman.md
google-datacatalog-sisense-connector/docs/developer-resources/sisense-apis.md
google-datacatalog-sisense-connector/setup.cfg
google-datacatalog-sisense-connector/setup.py
google-datacatalog-sisense-connector/src/google/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/authenticator.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/constants.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/__init__.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/authenticator_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/metadata_scraper_mocks.py
google-datacatalog-sisense-connector/tools/postman/Sisense REST API v1.postman_collection.json
google-datacatalog-sisense-connector/tools/postman/sisense-sample-environment.postman_environment.json

Set up the Sisense Connector package structure. 
1. Created a Python package with unit test support.
2. Created a `docs` folder with the initial developer resources.
3. Added a Postman collection to demonstrate foundational REST operations such as authentication, get folders, get dashboards and get widgets.
Check the static content, the Postman files, and run the unit tests.
Set up the Sisense Connector package structure.

Set up the Sisense Connector package structure

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/authenticator.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/metadata_scraper.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/rest_api_helper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/authenticator_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/metadata_scraper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/rest_api_helper_test.py

Added the features that allow the Sisense Connector to scrape folders' metadata.
Created the `scrape.RESTAPIHelper` and `scrape.MetadataScraper` classes, and their unit tests as well.
Run the unit tests
Added the features that allow the Sisense Connector to scrape folders' metadata.

Scrape Sisense Folders metadata

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/__init__.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/metadata_scraper_test.py

Added the feature that allows Sisense Connector to prepare Folder entries.
The tags will be tackled in the next PR.
Added the `prepare.AssembledEntryFactory` and `prepare.DataCatalogEntryFactory` classes, and their unit tests as well.
Added the feature that allows Sisense Connector to prepare Folder entries.

Prepare the Folder entries

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/rest_api_helper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper_test.py

Added a feature that allows the Sisense Connector to prepare Data Catalog Tags for Folders.
Added the `prepare.DataCatalogTagTemplateFactory`, `prepare.DataCatalogTagFactory`, and prepare.EntryRelationshipMapper classes, and their unit tests as well.
Added a feature that allows the Sisense Connector to prepare Data Catalog Tags for Folders.

Prepare the Folder tags

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/metadata_scraper.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/rest_api_helper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/metadata_scraper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/rest_api_helper_test.py

1. Added support for Sisense Dashboards metadata scraping.
2. I've also changed the REST API results pagination/deduping logic because I found a minor bug while working on the present feature (in a nutshell: `tuple()` does not work seamlessly with dicts that contain _complex_ values such as lists). I realized that pagination is not supported by `GET /dashboards` yet, but it was a bit late, so I decided to keep the fix to avoid trouble with the coming objects to be scraped.
The main change comprises 3 new methods and their unit tests:
1. `MetadataScraper.scrape_all_dashboards()`
2. `RESTAPIHelper.get_all_dashboards()`
3. `RESTAPIHelper.get_dashboard()`
Added support for …

Scrape Sisense Dashboards metadata

---

google-datacatalog-sisense-connector/docs/design-decisions.md
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py

Added the feature that allows Sisense Connector to prepare Dashboard entries.
The tags will be tackled in the next PR.
Added the `prepare.DataCatalogEntryFactory.make_entry_for_dashboard()` method, and its unit tests.
Added the feature that allows Sisense Connector to prepare Dashboard entries.
PS: This PR is part of the effort to deliver feature #70.

Prepare the Dashboard entries

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/docs/README.md
google-datacatalog-qlik-connector/docs/design-decisions.md

Moved the Qlik connector's design decisions documentation to the `docs` folder to keep it consistent with the file structure that has been used in the Sisense connector. The proposed structure is clearer as it promotes specific content in the `docs` folder instead of adding sections to the main `README.md` file.
1. Created and fulfilled the `docs/design-decisions.md` file.
2. Deleted the design decisions section of Qlik connector's main `README.md`.
Moved the Qlik connector's design decisions documentation to the `docs` folder.

Standardize the design decisions documentation

---

google-datacatalog-sisense-connector/.dockerignore
google-datacatalog-sisense-connector/Dockerfile

Added files that make it easier for users to run the connector using Docker.
Added the `Dockerfile` and `.dockerignore` files.
Build a Docker image and run the connector using it:
```shell script
docker build --rm --tag sisense2datacatalog .
docker run --rm --tty -v YOUR-CREDENTIALS_FILES_FOLDER:/data \
sisense2datacatalog \
--sisense-server $SISENSE2DC_SISENSE_SERVER \
--sisense-username $SISENSE2DC_SISENSE_USERNAME \
--sisense-password $SISENSE2DC_SISENSE_PASSWORD \
--datacatalog-project-id $SISENSE2DC_DATACATALOG_PROJECT_ID \
[--datacatalog-location-id $SISENSE2DC_DATACATALOG_LOCATION_ID]
```
> More docs on how to run the connector are coming soon.
Added files that make it easier for users to …

Add the Docker-related files

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper_test.py
google-datacatalog-sisense-connector/tools/scripts/cleanup_datacatalog.py

Added a feature that allows the Sisense Connector to prepare Data Catalog Tags for Dashboards.
Added the below methods and their unit tests as well:
- `prepare.DataCatalogTagTemplateFactory.make_tag_template_for_dashboard()`
- `prepare.DataCatalogTagFactory.make_tag_for_dashboard()`
- `prepare.EntryRelationshipMapper.__resolve_dashboard_mappings()`
Added a feature that allows the Sisense Connector to prepare Data Catalog Tags for Dashboards.

Prepare the Dashboard tags

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sync/metadata_synchronizer.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/sync/metadata_synchronizer_test.py
google-datacatalog-sisense-connector/tools/scripts/cleanup_datacatalog.py

Added features that allow the Sisense Connector to synchronize Dashboard metadata with Google Data Catalog.
1. Added the below methods and their unit test as well:
- `prepare.AssembledEntryFacory.__make_assembled_entry_for_dashboard()`
- `sync.MetadataSynchronizer.__scrape_dashboards()`
2. Performed minor refactorings to accommodate the changes.
Run the unit tests and, if possible, the connector in an integrated environment to check the results.
Added features that allow the Sisense Connector to synchronize Dashboard metadata with Google Data Catalog.

Synchronize the Dashboard metadata

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sync/metadata_synchronizer.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/sync/metadata_synchronizer_test.py

Added the parent folder name to the Folder tags.
1. Removed the `name` field from the Folder tags (it was redundant as their entry name is fulfilled with the same value).
2. Added the `parent_name` field to the Folder tags, providing users with more friendly metadata.
3. Update `MetadataSynchronizer.__scrape_folders()` in order to handle the changes in the tags.
4. Updated the unit tests.
Run the unit tests and, if possible, the connector in an integrated environment to check the results (this is a breaking change, so the cleanup script must be executed before running the present code).
Added the parent folder name to the Folder tags.

Add the parent folder name to the Folder tags

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/metadata_scraper.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/scrape/rest_api_helper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/metadata_scraper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/rest_api_helper_test.py

Added support for Sisense Widgets metadata scraping.
Added 2 new methods and their unit tests:
1. `MetadataScraper.scrape_widgets()`
2. `RESTAPIHelper.get_widgets()`
Added support for Sisense Widgets metadata scraping.
PS: This PR is part of the effort to deliver feature #70.

Scrape Sisense Widgets metadata

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper_test.py
google-datacatalog-sisense-connector/tools/scripts/cleanup_datacatalog.py

Added a feature that allows the Sisense Connector to prepare Data Catalog Tags for Widgets.
Added the below methods and their unit tests as well:
- `prepare.DataCatalogTagTemplateFactory.make_tag_template_for_widget()`
- `prepare.DataCatalogTagFactory.make_tag_for_widget()`
- `prepare.EntryRelationshipMapper.__resolve_widget_mappings()`
Added a feature that allows the Sisense Connector to prepare Data Catalog Tags for Widgets.
PS: This PR is part of the effort to deliver feature #70.

Prepare the Widget tags

---

google-datacatalog-sisense-connector/README.md
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sync/metadata_synchronizer.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/sync/metadata_synchronizer_test.py

Added features that allow the Sisense Connector to synchronize Widget metadata with Google Data Catalog.
1. Added the below methods and their unit test as well:
- `prepare.AssembledEntryFacory.__make_assembled_entries_for_dashboard()`
- `prepare.AssembledEntryFacory.__make_assembled_entry_for_widget()`
- `sync.MetadataSynchronizer.__scrape_widgets()`
2. Improved a few unit tests In order to have more accurate scenarios.
Run the unit tests and, if possible, the connector in an integrated environment to check the results.
Added features that allow the Sisense Connector to synchronize Widget metadata with Google Data Catalog.
PS: This PR is part of the effort to deliver #70.

Synchronize the Widget metadata

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py

Added features that allow the Sisense Connector to synchronize Dashboard and Widget filters as schema columns in Google Data Catalog.
Added the `__make_schema_for_dashboard()` and `__make_schema_for_widget()` methods to the `scrape.DataCatalogEntryFactory` class.
Added features that allow the Sisense Connector to synchronize Dashboard and Widget filters as schema columns in Google Data Catalog.
PS: This PR is part of the effort to deliver #70.

Make column schema for filters

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_template_factory_test.py

Added features that allow the Sisense Connector to create a Tag Template and Tags to store JAQL query metadata.
Added `DataCatalogTagTemplateFactory.make_tag_template_for_jaql()` and `DataCatalogTagFactory.__make_tag_for_jaql()`, and their unit tests as well.
Added features that allow the Sisense Connector to create a Tag Template and Tags to store JAQL query metadata.

Make JAQL query tags

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/sisense_connector_strings_helper.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/sisense_connector_strings_helper_test.py

Added a feature that allows the Sisense Connector to synchronize Widget fields as schema columns in Google Data Catalog.
1. Refactored the `__make_schema_for_widget()` method of `scrape.DataCatalogEntryFactory` so it delegates fields and filters columns generation.
2. Created the `DataCatalogEntryFactory.__make_fields_column_for_widget()` method.
3. Created the `DataCatalogEntryFactory.__make_filters_column_for_widget()` method.
4. Added the `prepare.SisenseConnectorStringsHelper` temporary class (instructions on how to remove it in the future are available in the class docs).
5. Add unit tests to fully cover the above changes.
Added a feature that allows the Sisense …

Make column schema for fields

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sync/metadata_synchronizer.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py
google-datacatalog-sisense-connector/tools/scripts/cleanup_datacatalog.py

Added features that enable the Sisense Connector to synchronize column-level tags comprising JAQL metadata for Dashboard filters, Widget fields, and filters in Google Data Catalog. These features make it possible for users to search Data Catalog to find where/which Sisense ElastiCube table fields are used in Widgets as data (fields) or filters, or Dashboards as filters.
1. Improved `AssembledEntryFactory.__make_assembled_entry_for_dashboard()` in order to create JAQL-based tags for Dashboard filters.
2. Improved `AssembledEntryFactory.__make_assembled_entry_for_widget()` in order to create JAQL-based tags for Widget fields and filters.
3. Added `DataCatalogTagFactory.make_tags_for_dashboard_filters()`.
4. Added …

Sync tags for JAQL queries

---

google-datacatalog-sisense-connector/README.md
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/constants.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/datacatalog_tag_factory_test.py

Added features that enable the Sisense connector to ingest JAQL formula metadata. The `formula` field is available for [JAQL queries with formulas](https://sisense.dev/guides/query/jaql/#step-7-adding-a-formula).
1. Added the `DataCatalogEntryFactory.__make_column_schema_for_jaql_formula()` method.
2. Added the `DataCatalogTagFactory.__make_tags_for_jaql_formula()` method.
3. Added unit tests to fully cover the new methods and required changes.
Run the unit tests and, if possible, the connector in an integrated environment to check the results.
Added features that enable the Sisense connector to ingest JAQL formula metadata.
PS: This PR is part of the effort to deliver #70.

Ingest JAQL formula metadata

---

google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/addons/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/addons/elasticube_dependency_finder.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/addons/elasticube_dependency_finder_test.py

Added the `addons.ElastiCubeDependencyFinder` class, the core of a new feature for the Sisense Connector CLI that is going to [allow users to easily find and display the specific fields and filters that depend on a given ElastiCube data source, table, and/or column](https://github.com/GoogleCloudPlatform/datacatalog-connectors-bi/projects/1#card-68317635).
Added the `addons.ElastiCubeDependencyFinder` class and its unit tests as well.
Added the `addons.ElastiCubeDependencyFinder` class.
PS 1: This PR is part of the effort to deliver #70.
PS 2: The CLI changes and related docs are already done but will be tackled in a separate PR to make the code review easier.

Find ElastiCube dependencies

---

google-datacatalog-sisense-connector/README.md
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/addons/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/addons/elasticube_dependency_printer.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sisense2datacatalog_cli.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/addons/__init__.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/addons/elasticube_dependency_finder_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/addons/elasticube_dependency_mocks.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/addons/elasticube_dependency_printer_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/sisense2datacatalog_cli_test.py

Enhanced Sisense2DataCatalog's CLI by adding the `find-elasticube-deps` option. The original catalog synchronization CLI tool is now under the `sync-catalog` option.
1. Refactored and improved `sisense.Sisense2DataCatalogCli` arg parsers. Two helper classes were created, `_SyncCatalogCliHelper` and `_FindElastiCubeDepsCliHelper`, each one setting up a specific CLI tool.
2. Added `addons.ElastiCubeDependencyPrinter` in order to print dependency finding results in a user-friendly fashion.
3. Added unit tests that fully cover the above code changes.
4. Update `README.md` by adding instructions on how to use the CLI.
Run the unit tests and, if possible, the connector in an integrated environment.
For the new `find-elasticube-deps` …

Add the find-elasticube-deps CLI option

---

google-datacatalog-sisense-connector/README.md
google-datacatalog-sisense-connector/setup.py

Set the Sisense Connector version to `0.1.0` and updated its main `README.md` file with instructions on how to install the package from PyPI (the package is going to be published after this PR gets merged).
Run `pip install --upgrade -e .` and make sure `google-datacatalog-sisense-connector-0.1.0` is installed.
Set version to `0.1.0` and updated the install instructions.
This PR is part of the effort to deliver #70.

Prepare the initial release

---

README.md
google-datacatalog-looker-connector/README.md
google-datacatalog-qlik-connector/README.md
google-datacatalog-sisense-connector/README.md
google-datacatalog-tableau-connector/README.md
google-datacatalog-tableau-connector/README_HOOK.md

Reorganized the badges in the main README files. The changes consist of:
1. The `license` badge is displayed in the repo and all connectors' main README files because it is general info.
2. The `Python package` badge is displayed only in the repo's main README because the CI workflow tests all connectors at once.
3. The `issues` badge is displayed only in the repo's main README because the link and counter refer to the repo and not to any specific connector.
4. The `pypi` badge is displayed in all connectors' main README files because it allows us to distinguish the link and version of each connector.
Browse the README files in the base branch.
Reorganized the badges in the README files.

Reorganize badges in the README files

---

google-datacatalog-qlik-connector/setup.py
google-datacatalog-sisense-connector/setup.py
google-datacatalog-tableau-connector/setup.py

Set up a Python 3.6 compatible version range for the `tomli` library, required by `pytest`.
Added `'tomli ~= 1.2.2'` to `setup.py`'s `tests_require` section. Only the Looker connector is not compatible with Python 3.6.
Run the Qlik, Sisense, and Tableau unit tests using Python 3.6.
Set up a Python 3.6 compatible version range for the `tomli` library, required by `pytest`.

Set up Python 3.6 compatible 'tomli' versions
