looker2datacatalog/README.md

I've reviewed the Looker connector setup instructions and found minor issues, fixing them with this PR.

Update Looker connector setup instructions

---

tableau2datacatalog/README.md

I've reviewed the Tableau connector setup instructions and found minor issues, fixing them with this PR.

Update Tableau connector setup instructions

---

README.md

ADD badge to README.md file

---

looker2datacatalog/README.md
tableau2datacatalog/README.md
tableau2datacatalog/src/google/datacatalog_connectors/tableau/scrape/metadata_api_constants.py

Added a TOC to README.md file.
Automatically created it, using: `npx markdown-toc -i README.md`
Verify the README.md file.
Makes the README.md file more readable.

ADD TOC to README.md

---

google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_tag_factory.py

Replaced `super()` method calls with `cls` calls.
Replaced `super()` method calls with `cls` calls.
Run the automated and maybe manual system tests.
Replaced `super()` method calls with `cls` calls.

Replace super() method calls with cls calls

---

google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/prepare/datacatalog_entry_factory.py
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/prepare/datacatalog_tag_factory.py

Replaced `super()` method calls with `self` calls where possible.
Replaced `super()` method calls with `self` calls.
Run automated and maybe manual tests.
Replace super() method calls with self calls

Replace super() method calls with self calls

---

google-datacatalog-tableau-connector/docs/developer-resources/postman.md
google-datacatalog-tableau-connector/tools/postman/Tableau REST API.postman_collection.json

Fixed documentation of the Postman collection for Tableau.
Fixed docs of the Postman collection for Tableau

Fix docs of the Postman collection for Tableau

---

google-datacatalog-looker-connector/setup.py
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/prepare/datacatalog_entry_factory.py
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/prepare/datacatalog_tag_factory.py
google-datacatalog-looker-connector/src/google/datacatalog_connectors/looker/prepare/datacatalog_tag_template_factory.py
google-datacatalog-looker-connector/system_tests/cleanup_results_test.py
google-datacatalog-looker-connector/system_tests/execution_results_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/assembled_entry_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/datacatalog_entry_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/datacatalog_tag_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-looker-connector/tests/google/datacatalog_connectors/looker/prepare/entry_relationship_mapper_test.py
google-datacatalog-looker-connector/tools/scripts/cleanup_datacatalog.py
google-datacatalog-tableau-connector/setup.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_tag_factory.py
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_tag_template_factory.py
google-datacatalog-tableau-connector/system_tests/cleanup_results_test.py
google-datacatalog-tableau-connector/system_tests/execution_results_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/prepare/entry_relationship_mapper_test.py
google-datacatalog-tableau-connector/tests/google/datacatalog_connectors/tableau/sync/dashboards_synchronizer_test.py
google-datacatalog-tableau-connector/tools/scripts/cleanup_datacatalog.py

Updated the connectors to use the Data Catalog client library v2.0.0
Followed the instructions from the 2.0.0 Migration Guide and other changes not covered in that guide.
Upgrade datacatalog client library version to 2.0.0

Upgrade datacatalog client library version to 2.0.0

---

google-datacatalog-looker-connector/README.md
google-datacatalog-tableau-connector/README.md
google-datacatalog-tableau-connector/docs/developer-resources/postman.md

Fixed a few links and typos in the documentation for Looker and Tableau connectors.
The main changes are in the `README.md` files of both projects. Comparing the current and proposed versions might be enough.
Fixed links and typos in the docs

Fix links and typos in the docs

---

google-datacatalog-tableau-connector/.coveragerc
google-datacatalog-tableau-connector/src/google/datacatalog_connectors/tableau/prepare/datacatalog_entry_factory.py

Simplified the string to datetime conversion in DataCatalogEntryFactory.
Removed unnecessary string handling and better used the incoming timestamp format.
Simplified the string to datetime conversion

Simplify string to datetime conversion

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/sync/metadata_synchronizer.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_entry_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/prepare/datacatalog_tag_template_factory_test.py
google-datacatalog-qlik-connector/tests/google/datacatalog_connectors/qlik/sync/metadata_synchronizer_test.py
google-datacatalog-qlik-connector/tools/postman/Qlik Sense Repository Service API.postman_collection.json

Added fields to fully synchronize the Apps available metadata.
Added and handled more fields to the App-related Entry, Tag Template, and Tag.
Added fields to fully synchronize the Apps available metadata.

Sync full Apps metadata

---

google-datacatalog-qlik-connector/README.md
google-datacatalog-qlik-connector/docs/developer-resources/README.md
google-datacatalog-qlik-connector/docs/developer-resources/postman.md
google-datacatalog-qlik-connector/docs/developer-resources/qlik-apis.md
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/engine_api_helper.py
google-datacatalog-qlik-connector/src/google/datacatalog_connectors/qlik/scrape/repository_services_api_helper.py
google-datacatalog-qlik-connector/tools/postman/Qlik Sense Repository Service API.postman_collection.json

Added links to relevant Qlik API docs and updated the Postman collection for QRS.
Added content to `.md` files, updated a few comments and exported a new collection from Postman.
There were no Python code changes, so it's only a matter of reading the updated docs.
Added links to relevant Qlik API docs and updated the Postman collection for QRS.

Add links to relevant Qlik API docs

---

google-datacatalog-tableau-connector/README.md
google-datacatalog-tableau-connector/docs/developer-resources/README.md
google-datacatalog-tableau-connector/docs/developer-resources/tableau.md

Added docs on how to set up a Tableau Server
Added/updated markdown files.
Check the git diff :).
Added docs on how to set up a Tableau Server.

Add docs on how to set up a Tableau Server

---

google-datacatalog-qlik-connector/setup.py

Increased the patch version to enable pushing the distribution package into PyPI.

Bump version: 0.1.0 → 0.1.1

---

google-datacatalog-qlik-connector/setup.py

Bumped the Qlik Sense connector's patch version to 0.1.2. 
Set the new version in `setup.py`.
Check the `version='0.1.2',` line in `setup.py`.
Bumped the Qlik Sense connector's patch version to 0.1.2.

Bump version: 0.1.1 → 0.1.2

---

google-datacatalog-looker-connector/docs/README.md
google-datacatalog-looker-connector/docs/developer-resources/README.md
google-datacatalog-looker-connector/docs/developer-resources/postman.md
google-datacatalog-qlik-connector/docs/README.md
google-datacatalog-qlik-connector/docs/developer-resources/README.md
google-datacatalog-qlik-connector/docs/developer-resources/postman.md
google-datacatalog-qlik-connector/docs/developer-resources/qlik-apis.md
google-datacatalog-tableau-connector/docs/README.md
google-datacatalog-tableau-connector/docs/developer-resources/README.md
google-datacatalog-tableau-connector/docs/developer-resources/postman.md
google-datacatalog-tableau-connector/docs/developer-resources/tableau.md

Added links to improve navigation through the additional documentation pages.
Added links to improve navigation through the additional documentation pages.

Improve the overall additional docs navigation

---

google-datacatalog-sisense-connector/setup.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sisense2datacatalog_cli.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sync/__init__.py
google-datacatalog-sisense-connector/src/google/datacatalog_connectors/sisense/sync/metadata_synchronizer.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/assembled_entry_factory_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/prepare/entry_relationship_mapper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/metadata_scraper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/scrape/rest_api_helper_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/sisense2datacatalog_cli_test.py
google-datacatalog-sisense-connector/tests/google/datacatalog_connectors/sisense/sync/metadata_synchronizer_test.py
google-datacatalog-sisense-connector/tools/scripts/cleanup_datacatalog.py

Added features that allow the Sisense Connector to synchronize Folder metadata with Google Data Catalog.
Added the `sync.MetadataSynchronizer` and `sisense.Sisense2DataCatalogCli` classes, and their unit tests as well.
Run the unit tests and, if possible, the connector in an integrated environment to check the results.
Added features that allow the Sisense Connector to synchronize Folder metadata with Google Data Catalog.

Synchronize the Folder metadata

---

google-datacatalog-sisense-connector/README.md
google-datacatalog-sisense-connector/docs/design-decisions.md

Added instructions on how to run the Sisense connector.
Updated the Sisense connector's `README.md` file.
Added instructions on how to run the Sisense connector.
PS: This PR is part of the effort to deliver feature #70.

Add instructions on how to run the connector

---

google-datacatalog-sisense-connector/tools/postman/Sisense REST API v1.postman_collection.json

Updated the Postman collection used as a reference for the Sisense connector.
Exported the most recent version using Postman.
Import and run the collection using Postman.
Updated the Postman collection used as a reference for the Sisense connector.

Update the Postman collection

---

README.md

Added a link to the Sisense Connector in the main README file.
Added a link to the Sisense Connector in the main README file.

Add link to the Sisense Connector
